version: '3'
services:
    python_uoc:
        build:
            context: ./
            dockerfile: .docker/Dockerfile
        volumes:
            - .:/usr/src/app
        environment:
            - PYTHONPATH=/usr/src/app/:$PYTHONPATH
        depends_on:
            - mongo_uoc
    mongo_uoc:
        image: "mongo"
        volumes:
            - ./dump:/dump
        ports:
            -   "27999:27017"
        command: mongod